-- Migration: insert_validacoes_checklist
-- Created at: 1762891704

INSERT INTO validacoes_sistema (funcionalidade, etapa, status) VALUES
('Usuarios - Listar', '1', 'pendente'),
('Usuarios - Criar', '1', 'pendente'),
('Usuarios - Editar', '1', 'pendente'),
('Usuarios - Inativar', '1', 'pendente'),
('Pacientes - Listar', '1', 'pendente'),
('Pacientes - Buscar', '1', 'pendente'),
('Pacientes - Cadastrar', '1', 'pendente'),
('Pacientes - Editar', '1', 'pendente'),
('Pacientes - Inativar', '1', 'pendente'),
('Feriados - Listar', '1', 'pendente'),
('Feriados - Adicionar', '1', 'pendente'),
('Feriados - Remover', '1', 'pendente'),
('Feriados - Sincronizar', '1', 'pendente'),
('Agenda - Visualizar', '1', 'pendente'),
('Agenda - Criar', '1', 'pendente'),
('Agenda - Editar', '1', 'pendente'),
('Agenda - Cancelar', '1', 'pendente'),
('Agenda - Conflitos', '1', 'pendente'),
('Fila - Listar', '1', 'pendente'),
('Fila - Adicionar', '1', 'pendente'),
('Fila - Reordenar', '1', 'pendente'),
('Fila - Modo', '1', 'pendente'),
('Fila - Chamar', '1', 'pendente'),
('WhatsApp - Individual', '2', 'pendente'),
('WhatsApp - Lote', '2', 'pendente'),
('App - Login', '2', 'pendente'),
('App - Chat IA', '2', 'pendente'),
('App - Agendar', '2', 'pendente'),
('App - Agendamentos', '2', 'pendente'),
('App - Historico', '2', 'pendente'),
('App - Perfil', '2', 'pendente'),
('IA - Perguntas', '2', 'pendente'),
('IA - Agendamento', '2', 'pendente'),
('IA - Exame', '2', 'pendente'),
('IA - Timeout', '2', 'pendente');;